init docker-with-zed

diff --git a/Docker/Dockerfile b/Docker/Dockerfile
--- a/Docker/Dockerfile
+++ b/Docker/Dockerfile
@@ -10,7 +10,7 @@ ARG PKGS_SIM="gz-harmonic"
 
 # ZED SDK args
 ARG ZED_SDK_URL="https://download.stereolabs.com/zedsdk/5.0/cu12/ubuntu22"
-ARG PKGS_ZED_SDK="zstd less cmake gnupg2 build-essential python3 python3-pip python3-dev python3-setuptools python3-wheel libusb-1.0-0-dev libgeographic-dev libdraco-dev zlib1g-dev lsb-release udev build-essential libpq-dev usbutils"
+ARG PKGS_ZED_SDK="ros-humble-zed-msgs zstd less cmake gnupg2 build-essential python3 python3-pip python3-dev python3-setuptools python3-wheel libusb-1.0-0-dev libgeographic-dev libdraco-dev zlib1g-dev lsb-release udev build-essential libpq-dev usbutils"
 ARG PKGS_PIP_ZED_SDK="cython numpy opencv-python-headless protobuf"
 
 ###########
@@ -32,23 +32,23 @@ ARG ZED_SDK_URL
 ARG ROS_DISTRO 
 
 RUN apt-get update -y && apt-get install -y --no-install-recommends \
-  ${PKGS_BASE} && \
+  ${PKGS_BASE} ${PKGS_ZED_SDK} && \
   apt-get clean && rm -rf /var/lib/apt/lists/*
 
 # Install the ZED SDK
-# RUN echo "[INFO] ZED SDK link: $ZED_SDK_URL" && \
-#   if [ "$(curl -L -I "${ZED_SDK_URL}" -o /dev/null -s -w '%{http_code}\n' | head -n 1)" = "200" ]; then \
-#   echo "[OKAY] ZedSDK URL exists"; \
-#   else \
-#   echo "[ERROR] ZedSDK URL does not point to a .run file or the file does not exist."; \
-#   exit 1; \
-#   fi; \
-#   wget -q -O ZED_SDK_Linux_Ubuntu.run ${ZED_SDK_URL} && \
-#   chmod +x ZED_SDK_Linux_Ubuntu.run && \
-#   ./ZED_SDK_Linux_Ubuntu.run -- silent skip_tools skip_cuda && \
-#   ln -sf /lib/x86_64-linux-gnu/libusb-1.0.so.0 /usr/lib/x86_64-linux-gnu/libusb-1.0.so && \
-#   rm ZED_SDK_Linux_Ubuntu.run && \
-#   rm -rf /var/lib/apt/lists/*
+RUN echo "[INFO] ZED SDK link: $ZED_SDK_URL" && \
+  if [ "$(curl -L -I "${ZED_SDK_URL}" -o /dev/null -s -w '%{http_code}\n' | head -n 1)" = "200" ]; then \
+  echo "[OKAY] ZedSDK URL exists"; \
+  else \
+  echo "[ERROR] ZedSDK URL does not point to a .run file or the file does not exist."; \
+  exit 1; \
+  fi; \
+  wget -q -O ZED_SDK_Linux_Ubuntu.run ${ZED_SDK_URL} && \
+  chmod +x ZED_SDK_Linux_Ubuntu.run && \
+  ./ZED_SDK_Linux_Ubuntu.run -- silent skip_tools && \
+  ln -sf /lib/x86_64-linux-gnu/libusb-1.0.so.0 /usr/lib/x86_64-linux-gnu/libusb-1.0.so && \
+  rm ZED_SDK_Linux_Ubuntu.run && \
+  rm -rf /var/lib/apt/lists/*
 
 # Install Gazebo Harmonic, dependency for osrf/vrx
 RUN curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
@@ -66,15 +66,15 @@ RUN /bin/bash -c "mkdir -p "${BOAT_WS}/src" && cd "${BOAT_WS}/src" && \
   apt-get update -y && \
   ls -la /opt/ros/${ROS_DISTRO} && source /opt/ros/${ROS_DISTRO}/setup.bash && \
   git clone --progress --verbose --recursive --depth 1 --branch ${VRX_BRANCH} https://github.com/${VRX_REPO}.git && \
-  # git clone --progress --verbose --recursive --depth 1 --branch ${ZED_BRANCH} https://github.com/${ZED_REPO}.git && \
+  git clone --progress --verbose --recursive --depth 1 --branch ${ZED_BRANCH} https://github.com/${ZED_REPO}.git && \
   cd ${BOAT_WS} && \
   rosdep update && rosdep install --from-paths src --ignore-src -r -y && \
   colcon build --parallel-workers $(nproc) --merge-install \
-  --event-handlers console_direct+ --base-paths src"
+  --event-handlers console_direct+ --base-paths src" \
 # These are for ZED SDK
-# --cmake-args ' -DCMAKE_BUILD_TYPE=Release' \
-# ' -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs' \
-# ' -DCMAKE_CXX_FLAGS=\"-Wl,--allow-shlib-undefined\"'"
+' --cmake-args  -DCMAKE_BUILD_TYPE=Release' \
+' -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs' \
+' -DCMAKE_CXX_FLAGS=\"-Wl,--allow-shlib-undefined\"'
 
 #####################
 # DEVELOPMENT IMAGE #
@@ -91,6 +91,9 @@ ARG BOAT_WS
 ARG ROS_DISTRO 
 ARG USER="root"
 ARG HOME="/${USER}"
+ARG PKGS_ZED_SDK
+ARG PKGS_PIP_ZED_SDK
+ARG ZED_SDK_URL
 
 ENV USER=${USER}
 ENV HOME=${HOME}
@@ -100,6 +103,26 @@ RUN mkdir -p ${BOAT_WS}
 ## .bashrc
 COPY .config/.bashrc ${HOME}/.bashrc
 COPY .config/.bash.d ${HOME}/.bash.d
+
+RUN apt-get update -y && apt-get install -y --no-install-recommends \
+  ${PKGS_BASE} ${PKGS_ZED_SDK} && \
+  apt-get clean && rm -rf /var/lib/apt/lists/*
+
+
+RUN echo "[INFO] ZED SDK link: $ZED_SDK_URL" && \
+  if [ "$(curl -L -I "${ZED_SDK_URL}" -o /dev/null -s -w '%{http_code}\n' | head -n 1)" = "200" ]; then \
+  echo "[OKAY] ZedSDK URL exists"; \
+  else \
+  echo "[ERROR] ZedSDK URL does not point to a .run file or the file does not exist."; \
+  exit 1; \
+  fi; \
+  wget -q -O ZED_SDK_Linux_Ubuntu.run ${ZED_SDK_URL} && \
+  chmod +x ZED_SDK_Linux_Ubuntu.run && \
+  ./ZED_SDK_Linux_Ubuntu.run -- silent skip_tools && \
+  ln -sf /lib/x86_64-linux-gnu/libusb-1.0.so.0 /usr/lib/x86_64-linux-gnu/libusb-1.0.so && \
+  rm ZED_SDK_Linux_Ubuntu.run && \
+  rm -rf /var/lib/apt/lists/*
+
 
 RUN curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
   echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] https://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null && \
